# Generated by Django 4.2.2 on 2023-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0003_alter_ocrmodel_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='report_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ocrmodel',
            name='patient_id',
            field=models.IntegerField(),
        ),
    ]
