# Generated by Django 4.2.2 on 2023-06-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_api', '0004_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='report_id',
            field=models.IntegerField(unique=True),
        ),
    ]
